# Generated by Django 4.0.6 on 2022-07-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_category_product_delete_vegetables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avialable',
            field=models.BooleanField(default='Доступно в продаже'),
        ),
    ]
