# Generated by Django 4.0.6 on 2022-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('full_support', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Название',
            },
        ),
    ]
